name: vazamento_gases_sync
description: ServiÃ§o Dart OO para sincronizar Firebase RTDB com MySQL
version: 0.1.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.6
  mysql1: ^0.19.2

dev_dependencies:
  pedantic: ^1.11.0